# Agent Collaboration Platform Project Definition
# TDDで開発された汎用的なエージェント連携プラットフォーム用設定

project_name: "debate_platform"
description: "AI debate system using agent collaboration platform"

# エージェント定義
agents:
  - id: "MODERATOR"
    type: "moderator"
    description: "Debate moderator and orchestrator"
  
  - id: "DEBATER_A"
    type: "debater"
    description: "Affirmative side debater"
  
  - id: "DEBATER_N"
    type: "debater"
    description: "Negative side debater"
  
  - id: "JUDGE_L"
    type: "judge"
    description: "Logic-focused judge"
  
  - id: "JUDGE_E"
    type: "judge"
    description: "Evidence-focused judge"
  
  - id: "JUDGE_R"
    type: "judge"
    description: "Rhetoric-focused judge"
  
  - id: "ANALYST"
    type: "analyst"
    description: "Debate performance analyst"

# A2Aメッセージバス設定
message_bus:
  type: "sqlite"
  db_path: "platform_messages.db"
  
# 初期タスク設定
initial_task:
  type: "debate"
  topic: "The impact of artificial intelligence on humanity"
  
# プラットフォーム設定
platform:
  timeout: 600  # 10分
  agent_check_interval: 5
  debug_mode: false
