services:
  service-name:
    build:
      context: ./${PROJECT_NAME}/.build
      dockerfile: Dockerfile
    image: ${PROJECT_NAME}_image
    volumes:
      - ./${PROJECT_NAME}:${CONTAINER_VOLUME:-/app}
      - ${STOCK_DATA}:${CONTAINER_STOCK:-/stock_data}
      - ${COMPANY_DATA}:${CONTAINER_COMPANY_DATA:-/company}
      - ${KABUTAN}:${CONTAINER_KABUTAN:-/kabutan}
    working_dir: ${CONTAINER_VOLUME:-/app}
    environment:
      - PYTHONPATH=${PYTHONPATH:-/app:/app/stock_price}
      - GEMINI_API_KEY=${GEMINI_API_KEY:-my_gemini_api_key}
      - AGENT_PLATFORM_CONFIG=${AGENT_PLATFORM_CONFIG:-/app/project.yml}
      - GITHUB_PAT=${GITHUB_PAT:-my_github_pat}
    # command: ["bash", "run.sh"]
    stdin_open: true
    tty: true